### ISSUE TITLE
feat: return matched pos

### ISSUE THREAD

**Issue by Akimotorakiyu** [scmmishra/pico-search#12]
## use case:
list: [{name:'hello'},{name:'other'}]
input: **e**
matched: [{name:'hello'},{name:'other'}]

when should highlight the matched char, we need pos of matched char to do that

1. h **e**🍺 llo
2. oth **e**🍺 r

thanks!

**Comment by scmmishra** [comment]
Hey @Akimotorakiyu given the search is fuzzy, and typo-tolerant. Getting the exact character to be matched would always be tricky, given the library was not designed for exact matches. You could explore something like [match-sorter](https://github.com/kentcdodds/match-sorter)

**Comment by Akimotorakiyu** [comment]
@scmmishra thanks!

**Comment by Akimotorakiyu** [comment]
> ref: https://github.com/kentcdodds/match-sorter/issues/144
